### ISSUE TITLE
executive installed and all working, web UI now erroring with "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

### ISSUE THREAD

**Issue by cwcrawley** [buzzingpixel/executive-ee#7]
I'm not sure if this is directly executive related, but it all appears to be working in command line now, but when I try to access the site or the CP - I get the following:

`The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly`

```
    #0 vendor/composer/composer/src/Composer/Factory.php(69): Composer\Factory::getUserDir()
    #1 vendor/composer/composer/src/Composer/Factory.php(160): Composer\Factory::getHomeDir()
    #2 vendor/composer/composer/src/Composer/Factory.php(303): Composer\Factory::createConfig(Object(Composer\IO\NullIO), '...')
    #3 vendor/composer/composer/src/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\NullIO), Array, false)
    #4 vendor/composer/composer/src/Composer/Console/Application.php(341): Composer\Factory::create(Object(Composer\IO\NullIO), NULL, false)
    #5 vendor/buzzingpixel/executive-ee/src/executive/addon.setup.php(30): Composer\Console\Application->getComposer()
    #6 ee/EllisLab/ExpressionEngine/Core/Application.php(218): require('...')
    #7 ee/EllisLab/ExpressionEngine/Core/Application.php(103): EllisLab\ExpressionEngine\Core\Application->addProvider('...')
    #8 ee/legacy/libraries/Core.php(103): EllisLab\ExpressionEngine\Core\Application->setupAddons('...')
    #9 ee/legacy/core/Controller.php(65): EE_Core->bootstrap()
    #10 ee/legacy/core/Controller.php(76): Base_Controller->__construct()
    #11 ee/legacy/core/Controller.php(99): EE_Controller->__construct()
    #12 ee/EllisLab/ExpressionEngine/Core/Core.php(228): CP_Controller->__construct()
    #13 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
    #14 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
    #15 EEFrontController.php(87): require_once('...')
    #16 public_html/admin.php(15): require('...')
    #16 public_html/admin.php(15): require('...') ```

**Comment by tjdraper** [comment]
That's odd. I haven't seen that one before. I also haven't used with EE 5 yet (which I'm looking forward to now that EE 5 is publicly out on GitHub). I'll see if I can replicate as soon as I can.

**Comment by tjdraper** [comment]
Can you check the version of Composer you are using? I'm seeing some indication via "the googles" that it may be a composer version bug.

**Comment by cwcrawley** [comment]
Version 1.7.3.

Yeah - googles seem to point to version issues, but most of them are with issues in the console, where as I have the issue when I HTTP in the browser.

**Comment by tjdraper** [comment]
I believe (hope) that beta 6 will address this issue.
